In [1]:
import torch
from torch import nn
import torch.nn.utils.prune as prune
import torch.nn.functional as F

In [2]:
device = torch.device("cuda")

class LeNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 5 *5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 18)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(slef.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(slef.conv2(x)), 2)
        x = x.veiw(-1, int(x.nelemnt() / x.shape[0]))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
model = LeNet().to(device=device)

        

In [3]:
module = model.conv1
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.1497],
          [ 0.0881, -0.1917,  0.0793]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.1745, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.3125]]],


        [[[-0.0715, -0.2817,  0.1551],
          [ 0.1208, -0.2097,  0.2736],
          [ 0.2998,  0.0112,  0.0589]]],


        [[[-0.0391, -0.1435, -0.2352],
          [ 0.1076, -0.1779,  0.1004],
          [ 0.2375,  0.0865,  0.2162]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.2033, -0.0821, -0.0886],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.1771,  0.1817,  0.0980],
          [ 0.0405,  0.0282,  0.1173],
          [-0.0824, -0.2734,  0.2926]]]], device='cuda:0', requires_grad=True)), ('bias', Parameter containing:
tensor([-0.1414,  0.2652,  0.0051, -0.0339,  0.2477,  0.0462], device='cuda:0',
       requires_grad=True))]


In [4]:
print(list(module.named_buffers()))

[]


In [5]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

In [6]:
print(list(module.named_parameters()))

[('bias', Parameter containing:
tensor([-0.1414,  0.2652,  0.0051, -0.0339,  0.2477,  0.0462], device='cuda:0',
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.1497],
          [ 0.0881, -0.1917,  0.0793]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.1745, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.3125]]],


        [[[-0.0715, -0.2817,  0.1551],
          [ 0.1208, -0.2097,  0.2736],
          [ 0.2998,  0.0112,  0.0589]]],


        [[[-0.0391, -0.1435, -0.2352],
          [ 0.1076, -0.1779,  0.1004],
          [ 0.2375,  0.0865,  0.2162]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.2033, -0.0821, -0.0886],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.1771,  0.1817,  0.0980],
          [ 0.0405,  0.0282,  0.1173],
          [-0.0824, -0.2734,  0.2926]]]], device='cuda:0', requires_grad=True))]


In [7]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1.],
          [1., 1., 0.],
          [1., 1., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 0.]]],


        [[[1., 1., 1.],
          [1., 1., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [1., 0., 0.],
          [1., 0., 1.]]],


        [[[1., 1., 1.],
          [0., 1., 0.],
          [1., 1., 1.]]],


        [[[0., 1., 1.],
          [1., 1., 0.],
          [0., 1., 1.]]]], device='cuda:0'))]


In [8]:
print(module.weight)

tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.0000],
          [ 0.0881, -0.1917,  0.0000]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.0000, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.0000]]],


        [[[-0.0715, -0.2817,  0.1551],
          [ 0.1208, -0.2097,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.0391, -0.1435, -0.2352],
          [ 0.1076, -0.0000,  0.0000],
          [ 0.2375,  0.0000,  0.2162]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.0000, -0.0821, -0.0000],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.0000,  0.1817,  0.0980],
          [ 0.0405,  0.0282,  0.0000],
          [-0.0000, -0.2734,  0.2926]]]], device='cuda:0',
       grad_fn=<MulBackward0>)


In [9]:
print(module._forward_pre_hooks)

OrderedDict([(0, <torch.nn.utils.prune.RandomUnstructured object at 0x7f1f78c2bca0>)])


In [10]:
prune.l1_unstructured(module, name="bias", amount=3)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

In [11]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.1497],
          [ 0.0881, -0.1917,  0.0793]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.1745, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.3125]]],


        [[[-0.0715, -0.2817,  0.1551],
          [ 0.1208, -0.2097,  0.2736],
          [ 0.2998,  0.0112,  0.0589]]],


        [[[-0.0391, -0.1435, -0.2352],
          [ 0.1076, -0.1779,  0.1004],
          [ 0.2375,  0.0865,  0.2162]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.2033, -0.0821, -0.0886],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.1771,  0.1817,  0.0980],
          [ 0.0405,  0.0282,  0.1173],
          [-0.0824, -0.2734,  0.2926]]]], device='cuda:0', requires_grad=True)), ('bias_orig', Parameter containing:
tensor([-0.1414,  0.2652,  0.0051, -0.0339,  0.2477,  0.0462], device='cuda:0',
       requires_grad=True))]


In [12]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1.],
          [1., 1., 0.],
          [1., 1., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 0.]]],


        [[[1., 1., 1.],
          [1., 1., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [1., 0., 0.],
          [1., 0., 1.]]],


        [[[1., 1., 1.],
          [0., 1., 0.],
          [1., 1., 1.]]],


        [[[0., 1., 1.],
          [1., 1., 0.],
          [0., 1., 1.]]]], device='cuda:0')), ('bias_mask', tensor([1., 1., 0., 0., 1., 0.], device='cuda:0'))]


In [13]:
print(module.bias)

tensor([-0.1414,  0.2652,  0.0000, -0.0000,  0.2477,  0.0000], device='cuda:0',
       grad_fn=<MulBackward0>)


In [14]:
print(module._forward_pre_hooks)

OrderedDict([(0, <torch.nn.utils.prune.RandomUnstructured object at 0x7f1f78c2bca0>), (1, <torch.nn.utils.prune.L1Unstructured object at 0x7f1f78c2b0d0>)])


In [15]:
prune.ln_structured(module, name="weight", amount=0.5, n=2, dim=0)

Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))

In [16]:
print(module.weight)

tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.0000],
          [ 0.0881, -0.1917,  0.0000]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.0000, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.0000]]],


        [[[-0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.0000, -0.0821, -0.0000],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000]]]], device='cuda:0',
       grad_fn=<MulBackward0>)


In [17]:
for hook in module._forward_pre_hooks.values():
    if hook._tensor_name == "weight":  # 가중치에 해당하는 훅을 선택
        break

print(list(hook))  # 컨테이너 내 가지치기 기법의 이력

[<torch.nn.utils.prune.RandomUnstructured object at 0x7f1f78c2bca0>, <torch.nn.utils.prune.LnStructured object at 0x7f1f78c2b220>]


In [18]:
print(model.state_dict().keys())

odict_keys(['conv1.weight_orig', 'conv1.bias_orig', 'conv1.weight_mask', 'conv1.bias_mask', 'conv2.weight', 'conv2.bias', 'fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias'])


In [19]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.1497],
          [ 0.0881, -0.1917,  0.0793]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.1745, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.3125]]],


        [[[-0.0715, -0.2817,  0.1551],
          [ 0.1208, -0.2097,  0.2736],
          [ 0.2998,  0.0112,  0.0589]]],


        [[[-0.0391, -0.1435, -0.2352],
          [ 0.1076, -0.1779,  0.1004],
          [ 0.2375,  0.0865,  0.2162]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.2033, -0.0821, -0.0886],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.1771,  0.1817,  0.0980],
          [ 0.0405,  0.0282,  0.1173],
          [-0.0824, -0.2734,  0.2926]]]], device='cuda:0', requires_grad=True)), ('bias_orig', Parameter containing:
tensor([-0.1414,  0.2652,  0.0051, -0.0339,  0.2477,  0.0462], device='cuda:0',
       requires_grad=True))]


In [20]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1.],
          [1., 1., 0.],
          [1., 1., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 1.],
          [1., 1., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[1., 1., 1.],
          [0., 1., 0.],
          [1., 1., 1.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]], device='cuda:0')), ('bias_mask', tensor([1., 1., 0., 0., 1., 0.], device='cuda:0'))]


In [21]:
print(module.weight)

tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.0000],
          [ 0.0881, -0.1917,  0.0000]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.0000, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.0000]]],


        [[[-0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.0000, -0.0821, -0.0000],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000]]]], device='cuda:0',
       grad_fn=<MulBackward0>)


In [22]:
prune.remove(module, 'weight')
print(list(module.named_parameters()))

[('bias_orig', Parameter containing:
tensor([-0.1414,  0.2652,  0.0051, -0.0339,  0.2477,  0.0462], device='cuda:0',
       requires_grad=True)), ('weight', Parameter containing:
tensor([[[[ 0.2146,  0.1737, -0.1622],
          [ 0.3243, -0.0103,  0.0000],
          [ 0.0881, -0.1917,  0.0000]]],


        [[[-0.1478, -0.0772,  0.2876],
          [ 0.0000, -0.1883,  0.1715],
          [ 0.2701, -0.3268, -0.0000]]],


        [[[-0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[-0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[ 0.1853, -0.1390,  0.0031],
          [ 0.0000, -0.0821, -0.0000],
          [-0.3312, -0.0722,  0.2321]]],


        [[[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000]]]], device='cuda:0', requires_grad=True))]


In [23]:
print(list(module.named_buffers()))

[('bias_mask', tensor([1., 1., 0., 0., 1., 0.], device='cuda:0'))]


In [24]:
new_model = LeNet()
for name, module in new_model.named_modules():
    # 모든 2D-conv 층의 20% 연결에 대해 가지치기 기법을 적용
    if isinstance(module, torch.nn.Conv2d):
        prune.l1_unstructured(module, name='weight', amount=0.2)
    # 모든 선형 층의 40% 연결에 대해 가지치기 기법을 적용
    elif isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.4)

print(dict(new_model.named_buffers()).keys())  # 존재하는 모든 마스크들을 확인

dict_keys(['conv1.weight_mask', 'conv2.weight_mask', 'fc1.weight_mask', 'fc2.weight_mask', 'fc3.weight_mask'])


In [27]:
model = LeNet()

parameters_to_prune = (
    (model.conv1, 'weight'),
    (model.conv2, 'weight'),
    (model.fc1, 'weight'),
    (model.fc2, 'weight'),
    (model.fc3, 'weight'),
)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.2,
)

In [28]:
print(
    "Sparsity in conv1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv1.weight == 0))
        / float(model.conv1.weight.nelement())
    )
)
print(
    "Sparsity in conv2.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv2.weight == 0))
        / float(model.conv2.weight.nelement())
    )
)
print(
    "Sparsity in fc1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc1.weight == 0))
        / float(model.fc1.weight.nelement())
    )
)
print(
    "Sparsity in fc2.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc2.weight == 0))
        / float(model.fc2.weight.nelement())
    )
)
print(
    "Sparsity in fc3.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc3.weight == 0))
        / float(model.fc3.weight.nelement())
    )
)
print(
    "Global sparsity: {:.2f}%".format(
        100. * float(
            torch.sum(model.conv1.weight == 0)
            + torch.sum(model.conv2.weight == 0)
            + torch.sum(model.fc1.weight == 0)
            + torch.sum(model.fc2.weight == 0)
            + torch.sum(model.fc3.weight == 0)
        )
        / float(
            model.conv1.weight.nelement()
            + model.conv2.weight.nelement()
            + model.fc1.weight.nelement()
            + model.fc2.weight.nelement()
            + model.fc3.weight.nelement()
        )
    )
)

Sparsity in conv1.weight: 1.85%
Sparsity in conv2.weight: 8.80%
Sparsity in fc1.weight: 22.19%
Sparsity in fc2.weight: 12.08%
Sparsity in fc3.weight: 10.45%
Global sparsity: 20.00%
